# Example requires existing PVC snapshot named `csi-pvc-snapshot-test`.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-snapshot-test-restore
spec:
  storageClassName: upcloud-block-storage-maxiops
  dataSource:
    name: csi-pvc-snapshot-test
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
