#kind: Pod
#apiVersion: v1
#metadata:
#  name: csi-app
#  labels:
#    app: csi-app
#spec:
#  containers:
#    - name: upcloud-test-pod
#      image: busybox
#      volumeMounts:
#        - mountPath: "/data"
#          name: upcloud-volume
#      command: [ "sleep", "1000000" ]
#  volumes:
#    - name: upcloud-volume
#      persistentVolumeClaim:
#        claimName: csi-pvc
#---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-app
  labels:
    app: csi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-app
  template:
    metadata:
      labels:
        app: csi-app
    spec:
      containers:
        - name: upcloud-test-pod
          image: busybox
          volumeMounts:
            - mountPath: "/data"
              name: upcloud-volume
          command: [ "sleep", "1000000" ]
      volumes:
        - name: upcloud-volume
          persistentVolumeClaim:
            claimName: csi-pvc
