project_name: upcloud-csi
builds:
  - id: upcloud-csi-plugin
    env:
      - CGO_ENABLED=0
    dir: .
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/UpCloudLtd/upcloud-csi/driver.version={{ if .IsSnapshot }}main{{ else }}{{ .Version }}{{ end }}
      - -X github.com/UpCloudLtd/upcloud-csi/driver.commit={{ .ShortCommit }}
      - -X github.com/UpCloudLtd/upcloud-csi/driver.gitTreeState={{ if .IsSnapshot }}dirty{{ else }}clean{{ end }}
    main: ./cmd/upcloud-csi-plugin
    binary: "upcloud-csi-plugin_v{{ .Version }}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
release:
  draft: true
  extra_files:
    - glob: ./deploy/kubernetes/*.yaml
