name: Lint

on:
  pull_request:

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout head
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Run golangci-lint-action
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.54
          args: --timeout 5m
          skip-cache: true
