name: UpCloud CSI driver integration test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Test Driver Integration
        env:
          UPCLOUD_TEST_USERNAME: ${{ secrets.UPCLOUD_TEST_USERNAME }}
          UPCLOUD_TEST_PASSWORD: ${{ secrets.UPCLOUD_TEST_PASSWORD }}
          UPCLOUD_TEST_HOSTNAME: ${{ secrets.UPCLOUD_TEST_HOSTNAME }}
        run: test-integration
