name: UpCloud CSI driver test

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - driver/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Run
        run: make test-driver
