name: UpCloud CSI driver test

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - internal/**
      - cmd/**
      - vendor/**
      - go.*
      - .github/**
      - test/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4

      - name: Test Driver
        run: sudo make test
